name: docker-push

on:
  push:
    branches: [ "main" ]

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set VERSION variable
        run: echo "VERSION=$(cat ./version)" >> $GITHUB_ENV
      - name: Docker compose build facetorch
        run: docker compose build facetorch
      - name: Tag image with version
        run: docker tag tomasgajarsky/facetorch:latest tomasgajarsky/facetorch:${{ env.VERSION }}
      - name: Login to Docker hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.io
      - name: Push images
        run: |
          docker push tomasgajarsky/facetorch:latest
          docker push tomasgajarsky/facetorch:${{ env.VERSION }}
  docker-push-gpu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set VERSION variable
        run: echo "VERSION=$(cat ./version)" >> $GITHUB_ENV
      - name: Docker compose build facetorch-gpu
        run: docker compose build facetorch-gpu-no-device
      - name: Tag image with version
        run: docker tag tomasgajarsky/facetorch-gpu:latest tomasgajarsky/facetorch-gpu:${{ env.VERSION }}
      - name: Login to Docker hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.io
      - name: Push images
        run: |
          docker push tomasgajarsky/facetorch-gpu:latest
          docker push tomasgajarsky/facetorch-gpu:${{ env.VERSION }}